apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: walkib-com-tls
spec:
  secretName: walkib-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: walkib.com
  dnsNames:
    - walkib.com
    - www.walkib.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - walkib.com
          - www.walkib.com
